$schema: http://json-schema.org/draft-04/schema#
title: pat - Prometheus Alert Testing utility
type: object
properties:
  name:
    type: string
  rules:
    $ref: "#/definitions/Rules"
  fixtures:
    type: array
    items:
      $ref: "#/definitions/Fixture"
  assertions: {}  # TODO
required:
  - name
  - rules
  - assertions
additionalProperties: false
definitions:
  Rules:
    type: object
    oneOf:
      - properties:
          fromFile:
            type: string
        required:
          - fromFile
      - properties:
          fromLiteral:
            type: string
        required:
          - fromLiteral
  Fixture:
    type: object
    properties:
      duration:
        type: string
        pattern: "^\\d+(ns|us|ms|s|m|h)$"
      metrics:
        type: array
        items:
          type: string
    required:
      - duration
      - metrics
